project_id = "rospqjcriewrjjzifmac"

[functions.send-push-notification]
verify_jwt = false

[functions.sales-inactivity-reminder]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false